app/projects/home/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from datetime import datetime
from urllib.parse import unquote
from app.services.firebase import Storage, DB, firestore

homeBlueprint = Blueprint(
    "home", __name__, static_folder="staticHome", template_folder="templates"
)


@homeBlueprint.route("/")
@homeBlueprint.route("/home")
def index():
    return render_template("index.html")


@homeBlueprint.route("/tentang_ima")
def about():
    return render_template("about.html")


@homeBlueprint.route("/review_buku")
def review_buku():
    data = (
        DB.collection("Review")
        .order_by("date_posted", direction=firestore.Query.DESCENDING)
        .stream()
    )
    datas = []
    for dt in data:
        d = dt.to_dict()
        d["id"] = dt.id
        datas.append(d)
    return render_template("review_buku.html", data=datas)


@homeBlueprint.route("/review_buku", methods=["GET", "POST"])
def buat_review():
    if request.method == "POST":
        image = request.files["foto"]
        blob = Storage.blob(image.filename)
        blob.upload_from_file(image, content_type=image.headers._list[1][1])
        blob.make_public()
        data = {
            "foto_buku": blob.public_url,
            "judul": request.form["judul"],
            "penulis": request.form["penulis"],
            "isi": request.form["ckeditor"],
            "tanggal": datetime.utcnow().strftime("%d %B, %Y"),
            "date_posted": datetime.utcnow().strftime("%Y/%m/%d"),
        }
        DB.collection("Review").document().set(data)
        return redirect(url_for("home.review_buku"))
    return render_template("review_buku.html")


@homeBlueprint.route("/review_buku/<uid>", methods=["GET", "POST"])
def konten_review(uid):
    data = DB.collection("Review").document(uid).get().to_dict()
    if request.method == "POST":
        datas = {
            "judul": request.form["judul"],
            "penulis": request.form["penulis"],
            "isi": request.form["ckeditor"],
        }
        if "foto" in request.files and request.files["foto"]:
            image = request.files["foto"]

            old_image = data["foto_buku"].split("/")[-1]
            old_blob = Storage.blob(unquote(old_image))
            if old_blob.exists():
                old_blob.delete()

            blob = Storage.blob(image.filename)
            blob.upload_from_file(image, content_type=image.headers._list[1][1])
            blob.make_public()
            datas["foto_buku"] = blob.public_url
        DB.collection("Review").document(uid).set(datas, merge=True)
        return redirect(url_for("home.review_buku"))
    user = DB.collection("Review").document(uid).get().to_dict()
    user["id"] = uid
    return render_template("konten_review.html", data=data, user=user)


@homeBlueprint.route("/review_buku/hapus/<uid>")
def hapus_review(uid):
    data = DB.collection("Review").document(uid).get().to_dict()

    old_image = data["foto_buku"].split("/")[-1]
    old_blob = Storage.blob(unquote(old_image))
    if old_blob.exists():
        old_blob.delete()

    DB.collection("Review").document(uid).delete()
    return redirect(url_for("home.review_buku"))


@homeBlueprint.route("/tulisan_kkn")
def tulisan_kkn():
    data = (
        DB.collection("Tulisan_KKN")
        .order_by("date_posted", direction=firestore.Query.DESCENDING)
        .stream()
    )
    datas = []
    for dt in data:
        d = dt.to_dict()
        d["id"] = dt.id
        datas.append(d)
    return render_template("tulisan_kkn.html", data=datas)


@homeBlueprint.route("/tulisan_kkn", methods=["GET", "POST"])
def buat_tulisan():
    if request.method == "POST":
        image = request.files["foto"]
        blob = Storage.blob(image.filename)
        blob.upload_from_file(image, content_type=image.headers._list[1][1])
        blob.make_public()
        data = {
            "foto_buku": blob.public_url,
            "judul": request.form["judul"],
            "penulis": request.form["penulis"],
            "isi": request.form["ckeditor"],
            "tanggal": datetime.utcnow().strftime("%d %B, %Y"),
            "date_posted": datetime.utcnow().strftime("%Y/%m/%d"),
        }
        DB.collection("Tulisan_KKN").document().set(data)
        return redirect(url_for("home.tulisan_kkn"))
    return render_template("tulisan_kkn.html")


@homeBlueprint.route("/tulisan_kkn/<uid>", methods=["GET", "POST"])
def konten_tulisan(uid):
    data = DB.collection("Tulisan_KKN").document(uid).get().to_dict()
    if request.method == "POST":
        datas = {
            "judul": request.form["judul"],
            "penulis": request.form["penulis"],
            "isi": request.form["ckeditor"],
        }
        if "foto" in request.files and request.files["foto"]:
            image = request.files["foto"]

            old_image = data["foto_buku"].split("/")[-1]
            old_blob = Storage.blob(unquote(old_image))
            if old_blob.exists():
                old_blob.delete()

            blob = Storage.blob(image.filename)
            blob.upload_from_file(image, content_type=image.headers._list[1][1])
            blob.make_public()
            datas["foto_buku"] = blob.public_url
        DB.collection("Tulisan_KKN").document(uid).set(datas, merge=True)
        return redirect(url_for("home.tulisan_kkn"))
    user = DB.collection("Tulisan_KKN").document(uid).get().to_dict()
    user["id"] = uid
    return render_template("konten_tulisan.html", data=data, user=user)


@homeBlueprint.route("/tulisan_kkn/hapus/<uid>")
def hapus_tulisan(uid):
    data = DB.collection("Tulisan_KKN").document(uid).get().to_dict()

    old_image = data["foto_buku"].split("/")[-1]
    old_blob = Storage.blob(unquote(old_image))
    if old_blob.exists():
        old_blob.delete()

    DB.collection("Tulisan_KKN").document(uid).delete()
    return redirect(url_for("home.tulisan_kkn"))

app/projects/home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>IMA-FEB-UH</title>
  <link rel="icon" type="image/x-icon" href="../staticHome/assets/favicon/favicon.ico" />
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-1YL10N2CBW"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    
    gtag('config', 'G-1YL10N2CBW');
  </script>
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="../staticHome/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
      <img src="../staticHome/assets/Logo/IMA.png" class="me-3" alt="" width="50">
      <a class="navbar-brand" href="#page-top">IMA FEB UH</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          {% block navbar %}
          {% endblock %}
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <!-- Footer-->
  <footer class="footer bg-black small text-center text-white-50">
    <div class="container px-4 px-lg-5">Copyright &copy; IMAFEBUH 2022</div>
    <p>#JayalahIMASelamanya</p>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="../staticHome/js/scripts.js"></script>
</body>
</html>

app/projects/home/templates/konten_review.html
{% extends 'base.html' %}
{% block navbar %}
  <li class="nav-item"><a class="nav-link" href="/review_buku">Review Page</a></li>
  {% if 'user' in session %}
  <li class="nav-item"><a class="nav-link" href="#buatReview" data-bs-toggle="modal" data-bs-target="#editReview">Edit Review</a></li>
  {% endif %}
{% endblock %}
{% block content %}
{{ ckeditor.load() }}
<!-- Masthead-->
<header class="masthead" style="height: 10px !important;">
  <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
    <div class="d-flex justify-content-center">
      <div class="text-center">
        <h1 class="mx-auto my-0 pt-5 text-uppercase">review buku <br>ima</h1>
        <!-- <a class="btn btn-primary mt-3" href="/tentang_ima">Tentang IMA</a> -->
        <i class="bi bi-arrow-down-circle-fill display-3 text-light text-opacity-50 mt-3"></i>
      </div>
    </div>
  </div>
</header>
<!-- Konten -->
<div class="container bg-light">
  <img src="{{ data.foto_buku }}" width="450px" class="img-fluid rounded mx-auto d-block my-5" alt="foto buku">
  <figure>
    <blockquote class="blockquote text-center">
      <p>Review Buku <span class="fst-italic fw-bold">"{{ data.judul }}"</span></p>
    </blockquote>
    <figcaption class="blockquote-footer text-center">
      Oleh <cite title="Source Title">{{ data.penulis }}</cite>
    </figcaption>
    <figcaption>
      <p>{{ data.isi|safe }}</p>
      <p class="font-monospace small text-muted">dipost pada <span class="fst-italic">{{ data.tanggal }}</span></p>
    </figcaption>
  </figure>
</div>
<!-- Modal Edit Review -->
<div class="modal fade" id="editReview" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editBeritaLabel">Form Berita</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('home.konten_review', uid=user.id) }}" method="POST" enctype="multipart/form-data">
          <div class="mb-3">
            <label for="judul" class="form-label">Judul Buku</label>
            <input type="text" class="form-control" id="judul" name="judul" value="{{ data.judul }}" required>
          </div>
          <div class="mb-3">
            <label for="penulis" class="form-label">Penulis Review</label>
            <input type="text" class="form-control" id="penulis" name="penulis" value="{{ data.penulis }}" required>
          </div>
          <div class="mb-3">
            <label for="foto" class="form-label">Foto Buku</label>
            <input class="form-control form-control-sm" id="foto" name="foto" type="file" accept="image/*" required>
          </div>
          <div class="mb-3">
            <label for="ckeditor" class="form-label">Isi Review</label>   
            {{ ckeditor.create() }}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Ubah</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/projects/home/templates/konten_tulisan.html
{% extends 'base.html' %}
{% block navbar %}
  <li class="nav-item"><a class="nav-link" href="/tulisan_kkn">Review Page</a></li>
  {% if 'user' in session %}
  <li class="nav-item"><a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#editTulisan">Edit Review</a></li>
  {% endif %}
{% endblock %}
{% block content %}
{{ ckeditor.load() }}
<!-- Masthead-->
<header class="masthead">
  <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
    <div class="d-flex justify-content-center">
      <div class="text-center">
        <h1 class="mx-auto my-0 pt-5 text-uppercase">tulisan Kema pengurus <br>ima</h1>
        <!-- <a class="btn btn-primary mt-3" href="/tentang_ima">Tentang IMA</a> -->
        <i class="bi bi-arrow-down-circle-fill display-3 text-light text-opacity-50 mt-3"></i>
      </div>
    </div>
  </div>
</header>
<!-- Konten -->
<div class="container bg-light">
  <img src="{{ data.foto_buku }}" width="450px" class="img-fluid rounded mx-auto d-block my-5" alt="foto buku">
  <figure>
    <blockquote class="blockquote text-center">
      <p><span class="fst-italic fw-bold">"{{ data.judul }}"</span></p>
    </blockquote>
    <figcaption class="blockquote-footer text-center">
      Oleh <cite title="Source Title">{{ data.penulis }}</cite>
    </figcaption>
    <figcaption>
      <p>{{ data.isi|safe }}</p>
      <p class="font-monospace small text-muted">dipost pada <span class="fst-italic">{{ data.tanggal }}</span></p>
    </figcaption>
  </figure>
</div>
<!-- Modal Edit Review -->
<div class="modal fade" id="editTulisan" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editBeritaLabel">Form Berita</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('home.konten_review', uid=user.id) }}" method="POST" enctype="multipart/form-data">
          <div class="mb-3">
            <label for="judul" class="form-label">Judul Buku</label>
            <input type="text" class="form-control" id="judul" name="judul" value="{{ data.judul }}" required>
          </div>
          <div class="mb-3">
            <label for="penulis" class="form-label">Penulis Review</label>
            <input type="text" class="form-control" id="penulis" name="penulis" value="{{ data.penulis }}" required>
          </div>
          <div class="mb-3">
            <label for="foto" class="form-label">Foto Buku</label>
            <input class="form-control form-control-sm" id="foto" name="foto" type="file" accept="image/*" required>
          </div>
          <div class="mb-3">
            <label for="ckeditor" class="form-label">Isi Review</label>   
            {{ ckeditor.create() }}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Ubah</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/projects/home/templates/review_buku.html
{% extends 'base.html' %}
{% block navbar %}
  <li class="nav-item"><a class="nav-link" href="/home">Home Page</a></li>
  {% if 'user' in session %}
  <li class="nav-item"><a class="nav-link" href="#buatReview" data-bs-toggle="modal" data-bs-target="#buatReview">Buat Review</a></li>
  <li class="nav-item"><a class="nav-link" href="/dashboard/">Dashboard</a></li>
  {% else %}
  <li class="nav-item"><a class="nav-link" href="/admin/login">Login</a></li>
  {% endif %}
{% endblock %}
{% block content %}
{{ ckeditor.load() }}
<!-- Masthead-->
<header class="masthead">
  <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
    <div class="d-flex justify-content-center">
      <div class="text-center">
        <h1 class="mx-auto my-0 pt-5 text-uppercase">review buku <br>ima</h1>
        <i class="bi bi-arrow-down-circle-fill display-3 text-light text-opacity-50 mt-3"></i>
      </div>
    </div>
  </div>
</header>
<!-- Review Buku -->
<div class="container">
  <div class="row">
    {% for d in data %}
    <div class="col-md-6">
      <div class="card my-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ d.foto_buku }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <a href="/review_buku/{{ d.id }}" class="text-decoration-none"><h5 class="card-title">{{ d.judul }}</h5></a>
              <p class="card-text"><small class="text-muted">{{ d.penulis }}</small></p>
              <div class="card-text overflow-hidden" style="max-height: 120px;min-height: 118px;">
                {{ d.isi|safe }}
              </div>
              <p class="card-text"><small class="text-muted">{{ d.tanggal }}</small></p>
            </div>
            {% if 'user' in session %}
            <a href="/review_buku/hapus/{{ d.id }}" class="btn btn-danger btn-small">Hapus</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- Buat Review -->
<div class="modal fade" id="buatReview" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="buatBeritaLabel">Form Berita</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('home.buat_review') }}" method="POST" enctype="multipart/form-data">
          <div class="mb-3">
            <label for="judul" class="form-label">Judul Buku</label>
            <input type="text" class="form-control" id="judul" name="judul" required>
          </div>
          <div class="mb-3">
            <label for="penulis" class="form-label">Penulis Review</label>
            <input type="text" class="form-control" id="penulis" name="penulis" required>
          </div>
          <div class="mb-3">
            <label for="foto" class="form-label">Foto Buku</label>
            <input class="form-control form-control-sm" id="foto" name="foto" type="file" accept="image/*" required>
          </div>
          <div class="mb-3">
            <label for="ckeditor" class="form-label">Isi Review</label>   
            {{ ckeditor.create() }}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/projects/home/templates/tulisan_kkn.html
{% extends 'base.html' %}
{% block navbar %}
<li class="nav-item"><a class="nav-link" href="/home">Home Page</a></li>
{% if 'user' in session %}
<li class="nav-item"><a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#buatTulisan">Buat Tulisan</a></li>
<li class="nav-item"><a class="nav-link" href="/dashboard/">Dashboard</a></li>
{% else %}
<li class="nav-item"><a class="nav-link" href="/admin/login">Login</a></li>
{% endif %}
{% endblock %}
{% block content %}
{{ ckeditor.load() }}
<!-- Masthead-->
<header class="masthead">
  <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
    <div class="d-flex justify-content-center">
      <div class="text-center">
        <h1 class="mx-auto my-0 pt-5 text-uppercase">tulisan kema pengurus <br>ima</h1>
        <!-- <a class="btn btn-primary mt-3" href="/tentang_ima">Tentang IMA</a> -->
        <i class="bi bi-arrow-down-circle-fill display-3 text-light text-opacity-50 mt-3"></i>
      </div>
    </div>
  </div>
</header>
<!-- Review Buku -->
<div class="container">
  <div class="row">
    {% for d in data %}
    <div class="col-md-6">
      <div class="card my-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ d.foto_buku }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <a href="/tulisan_kkn/{{ d.id }}" class="text-decoration-none"><h5 class="card-title">{{ d.judul }}</h5></a>
              <p class="card-text"><small class="text-muted">{{ d.penulis }}</small></p>
              <p class="card-text"><small class="text-muted">{{ d.tanggal }}</small></p>
            </div>
            {% if 'user' in session %}
            <a href="/tulisan_kkn/hapus/{{ d.id }}" class="btn btn-danger btn-small">Hapus</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- Buat Review -->
<div class="modal fade" id="buatTulisan" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="buatBeritaLabel">Form Tulisan</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('home.buat_tulisan') }}" method="POST" enctype="multipart/form-data">
          <div class="mb-3">
            <label for="judul" class="form-label">Judul Buku</label>
            <input type="text" class="form-control" id="judul" name="judul" required>
          </div>
          <div class="mb-3">
            <label for="penulis" class="form-label">Nama Penulis</label>
            <input type="text" class="form-control" id="penulis" name="penulis" required>
          </div>
          <div class="mb-3">
            <label for="foto" class="form-label">Foto Buku</label>
            <input class="form-control form-control-sm" id="foto" name="foto" type="file" accept="image/*" required>
          </div>
          <div class="mb-3">
            <label for="ckeditor" class="form-label">Isi Tulisan</label>   
            {{ ckeditor.create() }}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}