app/projects/dashboard/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    url_for,
    session,
    abort,
    request,
)
from ..admin.views import (
    login_required,
    admin_required,
    kekasi_required,
)
from app.services.firebase import DB, firestore

# from ..admin.views import login_required

dashboardBlueprint = Blueprint("dashboard", __name__, template_folder="templates")

# CORE | DASHBOARD
@dashboardBlueprint.route("/")
@login_required
def dashboard():
    if "user" in session:
        if session["user"]["otorisasi"] != "verified":
            session.clear()
            abort(401)
    return render_template("dashboard.html")


# CORE | PENGURUS
@dashboardBlueprint.route("/pengurus")
@kekasi_required
@login_required
def pengurus():
    data = (
        DB.collection("users")
        .order_by("name", direction=firestore.Query.ASCENDING)
        .stream()
    )
    users = []
    for user in data:
        us = user.to_dict()
        us["id"] = user.id
        users.append(us)
    return render_template("pengurus.html", data=users)


@dashboardBlueprint.route("/pengurus/ubah/<uid>", methods=["GET", "POST"])
@admin_required
@login_required
def ubah_pengurus(uid):
    if request.method == "POST":
        data = {
            "name": request.form["name"],
            "email": request.form["email"],
            "departemen": request.form["departemen"],
            "nim": request.form["nim"],
            "level_akses": request.form["level_akses"],
            "otorisasi": request.form["otorisasi"],
        }
        DB.collection("users").document(uid).set(data, merge=True)
        flash("berhasil ubah data", "success")
        return redirect(url_for("dashboard.pengurus"))
    user = DB.collection("users").document(uid).get().to_dict()
    user["id"] = uid
    return render_template("ubah_pengurus.html", data=user)


@dashboardBlueprint.route("/pengurus/hapus/<uid>")
@admin_required
@login_required
def hapus_pengurus(uid):
    DB.collection("users").document(uid).delete()
    flash("Data berhasil dihapus", "success")
    return redirect(url_for("dashboard.pengurus"))


# ADMINISTRASI | MAHASISWA | KEMA
@dashboardBlueprint.route("/kema")
@admin_required
@login_required
def kema():
    data = (
        DB.collection("KEMA")
        .order_by("angkatan", direction=firestore.Query.ASCENDING)
        .stream()
    )
    kema = []
    for km in data:
        k = km.to_dict()
        k["id"] = km.id
        kema.append(k)
    return render_template("kema.html", data=kema)


@dashboardBlueprint.route("/kema/ubah/<uid>", methods=["GET", "POST"])
@admin_required
@login_required
def ubah_kema(uid):
    if request.method == "POST":
        data = {
            "name": request.form["name"],
            "angkatan": request.form["angkatan"],
            "status_kuliah": request.form["status_kuliah"],
        }
        DB.collection("KEMA").document(uid).set(data, merge=True)
        flash("berhasil ubah data", "success")
        return redirect(url_for("dashboard.kema"))
    user = DB.collection("KEMA").document(uid).get().to_dict()
    user["id"] = uid
    return render_template("ubah_kema.html", data=user)


@dashboardBlueprint.route("/kema/hapus/<uid>")
@admin_required
@login_required
def hapus_kema(uid):
    DB.collection("KEMA").document(uid).delete()
    flash("Data berhasil dihapus", "success")
    return redirect(url_for("dashboard.kema"))


# INVENTARIS | BUKU IMA
@dashboardBlueprint.route("buku", methods=["GET", "POST"])
@login_required
def buku():
    if request.method == "POST":
        data = {
            "kode_buku": request.form["kode_buku"],
            "judul_buku": request.form["judul_buku"],
            "penulis_buku": request.form["penulis_buku"],
            "keterangan_buku": request.form["keterangan_buku"],
        }
        DB.collection("BUKU").document().set(data)
        return redirect(url_for("dashboard.buku"))
    if request.method == "GET":
        # Paginate Data
        books_ref = DB.collection("BUKU").order_by("judul_buku").limit(25).stream()
        books = []
        for book in books_ref:
            b = book.to_dict()
            b["id"] = book.id
            books.append(b)

        last_book = list(books)[-1]
        last_pop = last_book["judul_buku"]

        next_books = (
            DB.collection("BUKU")
            .order_by("judul_buku")
            .start_after({"judul_buku": last_pop})
            .limit(25)
            .stream()
        )

        nexts_books = []
        for next_book in next_books:
            nb = next_book.to_dict()
            nb["id"] = next_book.id
            nexts_books.append(nb)
    return render_template("buku.html", books=books)

app/projects/dashboard/templates/baseDashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>{{ title }}</title>
  <link rel="icon" type="image/x-icon" href="../../../static/assets/favicon.ico" />
  <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
  <link href="../../../static/css/styles.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
</head>
<body class="sb-nav-fixed">
  <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="/">IMA FEB UH</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
      <div class="input-group">
        <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
        <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
      </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="#!">Settings</a></li>
          <li><a class="dropdown-item" href="#!">Activity Log</a></li>
          <li><hr class="dropdown-divider" /></li>
          <li><a class="dropdown-item" href="/admin/logout">Logout</a></li>
        </ul>
      </li>
    </ul>
  </nav>
  <div id="layoutSidenav">
    <div id="layoutSidenav_nav">
      <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
          <div class="nav">
            <div class="sb-sidenav-menu-heading">Core</div>
            <a class="nav-link" href="/dashboard">
              <div class="sb-nav-link-icon"><i class="bi bi-speedometer"></i>
              </div>
              Dashboard
            </a>
            {% if session ['user']['departemen'] == 'Kekasi' %}
            <a class="nav-link" href="/dashboard/pengurus">
              <div class="sb-nav-link-icon"><i class="bi bi-gear-fill"></i>
              </div>
              Pengurus
            </a>
            {% endif %}
            <div class="sb-sidenav-menu-heading">Administrasi</div>
            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
              <div class="sb-nav-link-icon"><i class="bi bi-person-lines-fill"></i></div>
              Mahasiswa
              <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
              <nav class="sb-sidenav-menu-nested nav">
                {% if session ['user']['level_akses'] == 'Super User' %}
                <a class="nav-link" href="/dashboard/kema">Kema</a>
                {% endif %}
                <a class="nav-link" href="layout-sidenav-light.html">Biodata Putih</a>
              </nav>
            </div>
            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#administrasi_divisi" aria-expanded="false" aria-controls="administrasi_divisi">
              <div class="sb-nav-link-icon"><i class="bi bi-people-fill"></i></div>
              Departemen
              <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="administrasi_divisi" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
              <nav class="sb-sidenav-menu-nested nav">
                <a class="nav-link" href="#">Kekasi</a>
                <a class="nav-link" href="#">Hubeks</a>
                <a class="nav-link" href="#">Keilmuan</a>
                <a class="nav-link" href="#">Pengaderan</a>
              </nav>
            </div>
            <!-- <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
              <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
              Departemen
              <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
              <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                  Authentication
                  <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                  <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="login.html">Login</a>
                    <a class="nav-link" href="register.html">Register</a>
                    <a class="nav-link" href="password.html">Forgot Password</a>
                  </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                  Error
                  <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                  <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="401.html">401 Page</a>
                    <a class="nav-link" href="404.html">404 Page</a>
                    <a class="nav-link" href="500.html">500 Page</a>
                  </nav>
                </div>
              </nav>
            </div> -->
            <div class="sb-sidenav-menu-heading">Inventaris</div>
            <a class="nav-link" href="/dashboard/buku">
              <div class="sb-nav-link-icon"><i class="bi bi-book-fill"></i></div>
              Buku IMA
            </a>
            <a class="nav-link" href="tables.html">
              <div class="sb-nav-link-icon"><i class="bi bi-collection-fill"></i></div>
              Aset IMA
            </a>
          </div>
        </div>
        <div class="sb-sidenav-footer">
          <div class="small">Logged in as:</div>
          {{ session.user.name }}
        </div>
      </nav>
    </div>
    <div id="layoutSidenav_content">
      <main>
        {% block _content %}
        {% endblock %}
      </main>
      <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
          <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; IMA FEB-UH 2022</div>
            <img src="../../../static/Logo/IMA.png" width=50px alt="">
            <!-- <div>
              <a class="text-decoration-none" href="#">Privacy Policy</a>
              &middot;
              <a class="text-decoration-none" href="#">Terms &amp; Conditions</a>
            </div> -->
          </div>
        </div>
      </footer>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  <script src="../../../static/js/scripts.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
  <script src="../../../static/demo/chart-area-demo.js"></script>
  <script src="../../../static/demo/chart-bar-demo.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
  <script src="../../../static/js/datatables-simple-demo.js"></script>
</body>
</html>

app/projects/dashboard/templates/buku.html
{% extends 'baseDashboard.html' %}
{% set title='Buku - IMA' %}

{% block _content %}
<div class="container-fluid px-4">
  <h1 class="mt-4">Buku IMA</h1>
  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Daftar Buku IMA
    </div>
    <div class="card-body">
      <table id="bukuIMA">
        <thead>
          <tr>
            <th>No.</th>
            <th>Kode Buku</th>
            <th>Judul Buku</th>
            <th>Penulis</th>
            <th>Ketersediaan</th>
          </tr>
        </thead>
        <tbody>
          {% for book in books %}
          <tr>
            <td>{{ loop.index }}</td>
            <td>{{ book.kode_buku }}</td>
            <td>{{ book.judul_buku }}</td>
            <td>{{ book.penulis_buku }}</td>
            {% if book.keterangan_buku == 'A' %}
            <td><span class="badge bg-success">Tersedia</span></td>
            {% elif book.keterangan_buku == 'B' %}
            <td><span class="badge bg-warning">Dipinjam</span></td>
            {% elif book.keterangan_buku == 'T' %}
            <td><span class="badge bg-danger">Tidak Tersedia</span></td>
            {% else %}
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Data Peminjam Buku IMA
    </div>
    <div class="card-body">
      <table id="datatablesSimple">
        <thead>
          <tr>
            <th>Nama</th>
            <th>Jurusan</th>
            <th>Organisasi</th>
            <th>Tanggal Peminjaman</th>
            <th>Tanggal Pengembalian</th>
            <th>Salary</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011/04/25</td>
            <td>$320,800</td>
          </tr>
          <tr>
            <td>Garrett Winters</td>
            <td>Accountant</td>
            <td>Tokyo</td>
            <td>63</td>
            <td>2011/07/25</td>
            <td>$170,750</td>
          </tr>
          <tr>
            <td>Ashton Cox</td>
            <td>Junior Technical Author</td>
            <td>San Francisco</td>
            <td>66</td>
            <td>2009/01/12</td>
            <td>$86,000</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div> -->
</div>
{% endblock %}

app/projects/dashboard/templates/dashboard.html
{% extends 'baseDashboard.html' %}
{% set title='Dashboard - IMA' %}

{% block _content %}
<div class="container-fluid px-4">
  <h1 class="mt-4">Dashboard</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
  </ol>
  <div class="row">
    <div class="col-xl-3 col-md-6">
      <div class="card bg-primary text-white mb-4">
        <div class="card-body">Primary Card</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <a class="small text-white stretched-link" href="#">View Details</a>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card bg-warning text-white mb-4">
        <div class="card-body">Warning Card</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <a class="small text-white stretched-link" href="#">View Details</a>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card bg-success text-white mb-4">
        <div class="card-body">Success Card</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <a class="small text-white stretched-link" href="#">View Details</a>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card bg-danger text-white mb-4">
        <div class="card-body">Danger Card</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <a class="small text-white stretched-link" href="#">View Details</a>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-6">
      <div class="card mb-4">
        <div class="card-header">
          <i class="fas fa-chart-area me-1"></i>
          Area Chart Example
        </div>
        <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
      </div>
    </div>
    <div class="col-xl-6">
      <div class="card mb-4">
        <div class="card-header">
          <i class="fas fa-chart-bar me-1"></i>
          Bar Chart Example
        </div>
        <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/projects/dashboard/templates/kema.html
{% extends 'baseDashboard.html' %}
{% set title='KEMA - IMA' %}

{% block _content %}
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    Data KEMA IMA FEB UH
  </div>
  <div class="container text-center" style="width: 100%">
    {% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
  </div>
  <div class="card-body">
    <table id="datatablesSimple">
      <thead>
        <tr>
          <th>Nama</th>
          <th>Angkatan</th>
          <th>Status Kuliah</th>
          <!-- <th>Age</th>
          <th>Start date</th>
          <th>Salary</th> -->
        </tr>
      </thead>
      <!-- <tfoot>
        <tr>
          <th>Nama</th>
          <th>Angkatan</th>
          <th>Status Kuliah</th>
          <th>Age</th>
          <th>Start date</th>
          <th>Salary</th>
        </tr>
      </tfoot> -->
      <tbody>
        {% for k in data %}
        <tr>
          <!-- bisa begini -->
          <td>{{ k.name }}</td>
          <!-- bisa juga begini -->
          <td>{{ k['angkatan'] }}</td>
          <td>{{ k['status_kuliah'] }}</td>
          <td class="text-center">
            <a href="/dashboard/kema/ubah/{{ k.id }}" class="btn btn-sm rounded-circle btn-outline-secondary"><i class="bi bi-pencil-fill"></i></a>
            <a href="/dashboard/kema/hapus/{{ k.id }}" class="btn btn-sm rounded-circle btn-outline-danger"><i class="bi bi-trash2-fill"></i></a>
          </td>
          <!-- <td>61</td>
          <td>2011/04/25</td>
          <td>$320,800</td> -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

app/projects/dashboard/templates/pengurus.html
{% extends 'baseDashboard.html' %}
{% set title='KEMA - IMA' %}

{% block _content %}
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    Data Pengurus Kema IMA FEB-UH Periode 2022
  </div>
  <div class="container text-center" style="width: 100%">
    {% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show mt-3" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
  </div>
  <div class="card-body">
    <table id="datatablesSimple">
      <thead>
        <tr>
          <th>Nama</th>
          <th>NIM</th>
          <th>Otorisasi</th>
          <th>Departemen</th>
          <!-- <th>Age</th>
          <th>Start date</th>
          <th>Salary</th> -->
        </tr>
      </thead>
      <!-- <tfoot>
        <tr>
          <th>Nama</th>
          <th>Angkatan</th>
          <th>Status Kuliah</th>
          <th>Age</th>
          <th>Start date</th>
          <th>Salary</th>
        </tr>
      </tfoot> -->
      <tbody>
        {% for p in data %}
        <tr>
          <!-- bisa begini -->
          <td>{{ p.name }}</td>
          <td>{{ p.nim }}</td>
          <!-- bisa juga begini -->
          <td>{{ p['otorisasi'] }}</td>
          <td>{{ p['departemen'] }}</td>
          <td class="text-center">
            <a href="/dashboard/pengurus/ubah/{{ p.id }}" class="btn btn-sm rounded-circle btn-outline-secondary"><i class="bi bi-pencil-fill"></i></a>
            <a href="/dashboard/pengurus/hapus/{{ p.id }}" class="btn btn-sm rounded-circle btn-outline-danger"><i class="bi bi-trash2-fill"></i></a>
          </td>
          <!-- <td>61</td>
          <td>2011/04/25</td>
          <td>$320,800</td> -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

app/projects/dashboard/templates/ubah_kema.html
{% extends 'baseDashboard.html' %}
{% set title='KEMA|UBAH - IMA' %}
{% block _content %}
<div class="container mt-3">
  <div class="container text-center" style="width: 100%">
    {% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
  </div>
  <h1>Ubah Data</h1>
  <form action="{{ url_for('dashboard.ubah_kema', uid=data.id) }}" method="POST">
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Nama Lengkap</span>
      <input type="text" class="form-control" name="name" value="{{ data.name }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Angkatan</span>
      <input type="text" class="form-control" name="angkatan" value="{{ data.angkatan }}">
    </div>
    <select class="form-select mb-3" aria-label="Default select example" name="status_kuliah">
      <option selected value="">{{ data.status_kuliah }}</option>
      <option value="Lulus">Lulus</option>
      <option value="Belum Lulus">Belum Lulus</option>
    </select>
    <div>
      <div class="d-grid"><button type="submit" id="submit" class="btn btn-primary btn-block">Ubah</button></div>
    </div>
  </form>
</div>
{% endblock %}

app/projects/dashboard/templates/ubah_pengurus.html
{% extends 'baseDashboard.html' %}
{% set title='KEMA - IMA' %}
{% block _content %}
<div class="container mt-3">
  <h1>Ubah Data</h1>
  <form action="{{ url_for('dashboard.ubah_pengurus', uid=data.id) }}" method="POST">
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Nama Lengkap</span>
      <input type="text" class="form-control" name="name" value="{{ data.name }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">NIM</span>
      <input type="text" class="form-control" name="nim" value="{{ data.nim }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Email</span>
      <input type="text" class="form-control" name="email" value="{{ data.email }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Departemen</span>
      <input type="text" class="form-control" name="departemen" value="{{ data.departemen }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Level Akses</span>
      <input type="text" class="form-control" name="level_akses" value="{{ data.level_akses }}">
    </div>
    <select class="form-select mb-3" aria-label="Default select example" name="otorisasi">
      <option selected value="">{{ data.otorisasi }}</option>
      <option value="verified">Verified</option>
      <option value="0">Revoke</option>
    </select>
    <div>
      <div class="d-grid"><button type="submit" id="submit" class="btn btn-primary btn-block">Ubah</button></div>
    </div>
  </form>
</div>
{% endblock %}